title: Computer Conference Deadlines
description: Countdowns to top Compiler/Systems conference deadlines
author: Heelim Choi

domain: "heelim.github.io"
baseurl: ""

twitter_hashtag: 
github_username: heelim
github_repo: heelim.github.io

markdown: kramdown
ga_id:

include: ['_pages']
